### ISSUE TITLE
[BUG] ##[warning]Unexpected input(s) 'excludeTitle', 'checkAllCommitMessages', 'accessToken'.

### ISSUE THREAD

**Issue by ItaloYeltsin** [GsActions/commit-message-checker#19]
We forgot to add these argument to the list of valid arguments.

**args:**
```
excludeDescription: true 
excludeTitle: true
checkAllCommitMessages: true 
accessToken: ${{ secrets.GITHUB_TOKEN }}
```

**warning message:**
```
##[warning]Unexpected input(s) 'excludeTitle', 'checkAllCommitMessages', 'accessToken', valid inputs are ['pattern', 'flags', 'error', 'excludeDescription']
```

**Comment by ItaloYeltsin** [comment]
#20 fixes this.

**Comment by gilbertsoft** [comment]
@ItaloYeltsin Thanks for closing, didn't see it wasn't linked to the PR.

BTW I'm still working on the new release with some little changes see https://github.com/GsActions/commit-message-checker/pull/21
