### ISSUE TITLE
Checks fails after merging pull request

### ISSUE THREAD

**Issue by ernestkamara** [GsActions/commit-message-checker#29]
Hi,
Is there any way to disable checking title after merging a pull request?

Here is my WIP workflow:

```
name: 'Commit Message Check'
on: [push]
#  pull_request:
#    types:
#      - opened
#      - edited
#      - reopened
#      - synchronize
#  push:
#    branches:
#      - main
#      - 'releases/*'

jobs:
  check-commit-message:
    name: Check Commit Message
    runs-on: ubuntu-latest
    steps:
      - name: Check Commit Type
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: '^(add|remove|fix|chore)\([^\{\}\[\]\(\)]+?\) : '
          flags: 'gm'
          error: 'Your first line has to contain a commit type like "add|remove|fix|chore(...) : ".'
      - name: Check Line Length
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: '^[^#].{74}'
          error: 'The maximum line length of 74 characters is exceeded.'
          excludeDescription: 'true' # optional: this excludes the description body of a pull request
          excludeTitle: 'true' # optional: this excludes the title of a pull request
          #checkAllCommitMessages: 'true' # optional: this checks all commits associated with a pull request
          #accessToken: ${{ secrets.GITHUB_TOKEN }} # github access token is only required if checkAllCommitMessages is true
      - name: Check for Resolves / Fixes
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: '^(Closes|Fixes) : \#((?!([A-Z0-9a-z]{1,10})-?$)[A-Z]{1}[A-Z0-9]+-[1-9][0-9]*).+$'
          error: 'You need at least one "Closes|Fixes : #<Jira issue key>" line.' 
```
Successful Commit check:
<img width="800" alt="Screenshot 2020-11-13 at 09 03 48" src="https://user-images.githubusercontent.com/502798/99043968-4dc15900-258f-11eb-92ce-f977d969248d.png">

Failed checks after merging.
<img width="1145" alt="Screenshot 2020-11-13 at 09 04 27" src="https://user-images.githubusercontent.com/502798/99044007-5f0a6580-258f-11eb-8822-3546a80e15e7.png">
<img width="1130" alt="Screenshot 2020-11-13 at 09 04 41" src="https://user-images.githubusercontent.com/502798/99044009-603b9280-258f-11eb-92ed-b01817fc9b27.png">

Thanks.

**Comment by gilbertsoft** [comment]
Hi @ernestkamara,

yes, this should be possible by setting `excludeDescription: 'true'` and `excludeTitle: 'true'` in the related step `Check Commit Type`.

**Comment by ernestkamara** [comment]
Hi @gilbertsoft 
That is the settings I have above but not working as described above.

**Comment by gilbertsoft** [comment]
No, you have it set for the step `Check Line Length` only. Copy these lines to the first step and it should work.

**Comment by ernestkamara** [comment]
Like this?
```
name: 'Commit Message Check'
on: [push]
#  pull_request:
#    types:
#      - opened
#      - edited
#      - reopened
#      - synchronize
#  push:
#    branches:
#      - main
#      - 'releases/*'

jobs:
  check-commit-message:
    name: Check Commit Message
    runs-on: ubuntu-latest
    steps:
      - name: Check Commit Type
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: '^(add|remove|fix|chore)\([^\{\}\[\]\(\)]+?\) : '
          excludeDescription: 'true' # optional: this excludes the description body of a pull request
          excludeTitle: 'true' # optional: this excludes the title of a pull request
          flags: 'gm'
          error: 'Your first line has to contain a commit type like "add|remove|fix|chore(...) : ".'
      - name: Check Line Length
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: '^[^#].{74}'
          error: 'The maximum line length of 74 characters is exceeded.'
          excludeDescription: 'true' # optional: this excludes the description body of a pull request
          excludeTitle: 'true' # optional: this excludes the title of a pull request
          #checkAllCommitMessages: 'true' # optional: this checks all commits associated with a pull request
          #accessToken: ${{ secrets.GITHUB_TOKEN }} # github access token is only required if checkAllCommitMessages is true
      - name: Check for Resolves / Fixes
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: '^(Closes|Fixes) : \#((?!([A-Z0-9a-z]{1,10})-?$)[A-Z]{1}[A-Z0-9]+-[1-9][0-9]*).+$'
          error: 'You need at least one "Closes|Fixes : #<Jira issue key>" line.'
```

**Comment by gilbertsoft** [comment]
Yes, exactly. Perhaps you like to add it also to the last step if you wanna exclude this step too for the pull request.

**Comment by gilbertsoft** [comment]
An other interesting option could be the `checkAllCommitMessages` setting if you have pull requests with multiple commits.

**Comment by ernestkamara** [comment]
But shouldn't the above only run `on: [push]` and not on PR?

**Comment by ernestkamara** [comment]
I am trying to just check the commit message on: [push] and planned to create a new workflow for PRs since we have some templates. Does this sound feasible?

**Comment by gilbertsoft** [comment]
If you pull the pull request using the merge strategy you will always end with an additional merge commit. That's your problem here.

**Comment by gilbertsoft** [comment]
Yes, you can always use the action in multiple workflows. The action is designed as flexible as possible to support all possible cases.

**Comment by ernestkamara** [comment]
Will this work for just checking the commit message and not the PR?
```

name: 'Commit Message Check'
on: [push]
jobs:
  check-commit-message:
    name: Check Commit Message
    runs-on: ubuntu-latest
    steps:
      - name: Check Commit Type
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: '^(add|remove|fix|chore)\([^\{\}\[\]\(\)]+?\) : '
          flags: 'gm'
          error: 'Your first line has to contain a commit type like "add|remove|fix|chore(...) : ".'
          excludeDescription: 'true'
          excludeTitle: 'true'
      - name: Check Line Length
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: '^[^#].{74}'
          error: 'The maximum line length of 74 characters is exceeded.'
          excludeDescription: 'true' # optional: this excludes the description body of a pull request
          excludeTitle: 'true' # optional: this excludes the title of a pull request
      - name: Check for Resolves / Fixes
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: '^(Closes|Fixes) : \#((?!([A-Z0-9a-z]{1,10})-?$)[A-Z]{1}[A-Z0-9]+-[1-9][0-9]*).+$'
          error: 'You need at least one "Closes|Fixes : #<Jira issue key>" line.'
          excludeDescription: 'true'
          excludeTitle: 'true'

```

**Comment by gilbertsoft** [comment]
Perhaps you should do some tests with the various merge strategies, there are currently 3 at Github:

- merge
- squash
- rebase

![grafik](https://user-images.githubusercontent.com/25326036/99046615-4d2ac180-2593-11eb-8a47-f222cbe94557.png)

There are big differences in this three strategies. You first need to understand what's exactly going on here and decide which ones you like to support for your repository.

The problem with your configuration above is that as already mentioned if you merge by a merge commit there will be an additional commit created. You can not exclude that commit from the check so you also have to add a rule for it to "exclude" it from the check. Normally you better setup a workflow for a PR and not a push like you did. It's to late to change something after the push has done.

**Comment by gilbertsoft** [comment]
Here you see an example workflow, we use the squash strategy only in this repository. Means all commits are squashed to one commit and the title and description of the pull request are takken for the final commit:

https://github.com/benjaminkott/bootstrap_package/blob/master/.github/workflows/check-pr.yml

**Comment by gilbertsoft** [comment]
Imho using a push event is normally not what you want. If you use the merge strategy the settings checkAllCommitMessages, excludeDescription and excludeTitle are normally interesting and should be set to true.

**Comment by ernestkamara** [comment]
Thanks @gilbertsoft 
The squash strategy seems to be working with my commit check above.

**Comment by ernestkamara** [comment]
@gilbertsoft  Here is my WIP pr-check.
Anything I should change?

```
name: 'Check Pull Request'
on: [pull_request]

jobs:
  check-commit-message:
    name: Check Pull Request Message
    runs-on: ubuntu-latest
    steps:
      - name: Check Pull Request Type
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: '^(Feature|Bugfix|TechDebt)\([^\{\}\[\]\(\)]+?\) : '
          flags: 'gm'
          error: 'Your first line has to contain a pull request title like "Feature|Bugfix|TechDebt(...) : ".'

      - name: Check Pull Request Requirments
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: '^(Description|References|Solution|Tested)'
          flags: 'gm'
          error: 'Missing required fields. Description, References, Solution, Tested are all required.'
      - name: Check for Closes or Fixes
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: '^(Closes|Fixes) : \#((?!([A-Z0-9a-z]{1,10})-?$)[A-Z]{1}[A-Z0-9]+-[1-9][0-9]*).+$'
          error: 'You need at least one "Closes|Fixes : #<Jira issue key>" line.'
```

**Comment by gilbertsoft** [comment]
Yes, because there is no additional merge commit created. But as said you should rethink your whole workflow here, using the pull event is really not what you want here I hardly guess.

It's not clear to me what you like to have checked with your new workflow in detail. Currently you check the title in the first step, the last step checks for a line in the PR title or description and with the second step you check the first commit. I guess the last one should also check the PR and not the commit and if so you have to remove the excludeDescription and excludeTitle. Also I'm not sure if the usage of flags is really correct.

**Comment by ernestkamara** [comment]
I would have loved to have a single workflow for both commit and PR. The problem is that PR requires more details then a commit. I would like to have a structured commit message that provide insights into what has changed and why it changed over the caurse of time. 

Maybe, I just need the pr checks

I am trying to check the following:

-  The title/first like to meet our requirement as 
-  Then verify that the description contains all these sections "Description|References|Solution|Tested"
-  Then the last line to be like Closes|Fixes : #<Jira issue key>" line.

**Comment by gilbertsoft** [comment]
Yes, checking a PR is normally enough. Just make sure nobody can push commits directly to a main branch, this should only be possible by a PR.

Also a good option would be only allowing squash merges, then you just can concentrate to the PR title and description with the checks.

According to your description the workflow should look similar to this (disclaimer: not tested):

```
name: 'Check Pull Request'
on: [pull_request]

jobs:
  check-commit-message:
    name: Check Pull Request Message
    runs-on: ubuntu-latest
    steps:
      - name: Check Pull Request Type
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: '^(Feature|Bugfix|TechDebt)\([^\{\}\[\]\(\)]+?\) : '
          flags: ''
          error: 'Your first line has to contain a pull request title like "Feature|Bugfix|TechDebt(...) : ".'
      - name: Check for Description
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: '^Description:$'
          error: 'Missing required field Description.'
      - name: Check for References
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: '^References:$'
          error: 'Missing required field References.'
      - name: Check for Solution
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: '^Solution:$'
          error: 'Missing required field Solution.'
      - name: Check for Tested
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: '^Tested:$'
          error: 'Missing required field Tested.'
      - name: Check for Closes or Fixes
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: '^(Closes|Fixes): \#((?!([A-Z0-9a-z]{1,10})-?$)[A-Z]{1}[A-Z0-9]+-[1-9][0-9]*).+$'
          error: 'You need at least one "Closes|Fixes : #<Jira issue key>" line.'
```

**Comment by ernestkamara** [comment]
Thanks, @gilbertsoft, make sense. But adding new commits to the PR wasn't checked!
Should I add checkAllCommitMessages?

**Comment by ernestkamara** [comment]
Would this work?
```
name: 'Check Pull Request'
on: [ pull_request ]

jobs:
  check-commit-message:
    name: Check Pull Request Message
    runs-on: ubuntu-latest
    steps:
      - name: Check Pull Request Type
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: '^(Add|Remove|Bugfix|Chore|Feature|TechDebt)\([^\{\}\[\]\(\)]+?\) : '
          error: 'Your first line has to contain a pull request title like "Add|Remove|Fix|Chore|Feature|TechDebt(...) : ".'
          checkAllCommitMessages: 'true'
          accessToken: ${{ secrets.GITHUB_TOKEN }}
      - name: Check for Description
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: 'Description:[\r\n]+([^\r\n]+)'
          error: 'Missing required field Description.'
          checkAllCommitMessages: 'true'
          accessToken: ${{ secrets.GITHUB_TOKEN }}
      - name: Check for Solution
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: 'Solution:[\r\n]+([^\r\n]+)'
          error: 'Missing required field Solution.'
          checkAllCommitMessages: 'true'
          accessToken: ${{ secrets.GITHUB_TOKEN }}
      - name: Check for Tested
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: 'Tested?[\r\n]+([^\r\n]+)'
          error: 'Missing required field How Has This Been Tested.'
          checkAllCommitMessages: 'true'
          accessToken: ${{ secrets.GITHUB_TOKEN }}
      - name: Check for References
          uses: gsactions/commit-message-checker@v1
          with:
            pattern: 'References:[\r\n]+([^\r\n]+)'
            error: 'Missing required field References.'
            checkAllCommitMessages: 'true'
            accessToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Check for Closes or Fixes
          uses: gsactions/commit-message-checker@v1
          with:
            pattern: '^(Closes|Fixes) : \#((?!([A-Z0-9a-z]{1,10})-?$)[A-Z]{1}[A-Z0-9]+-[1-9][0-9]*).+$'
            error: 'You need at least one "Closes|Fixes : #<Jira issue key>" line.'
            checkAllCommitMessages: 'true'
            accessToken: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by gilbertsoft** [comment]
If you squash merge the commit messages of all commits are ignored so for squash merges this makes no sense imho.

**Comment by ernestkamara** [comment]
Meaning its late for the Check to rerun?

**Comment by gilbertsoft** [comment]
You should really try to understand how the various merge strategies are working as said before. Then you have to make a decision how you would like to work. Of course it's also possible to use multiple strategies but this makes the checks very hard.

And no, it's not to late. Once the PR gets merged you can not longer change or fix something ofc. But before everything is possible.

Currently it looks like I have a bug here see https://github.com/GsActions/commit-message-checker/issues/30

**Comment by ernestkamara** [comment]
I have worked with all the various type of merge strategies before and I personally prefered `squash merge`. That's why I started by having separate checks for the commit and one for PRs.

**Comment by gilbertsoft** [comment]
Then you should know and understand that the option `checkAllCommitMessages: 'true'` does not make sense for a squash commit as all single commits get lost but for a merge or rebase one ;)

TBH I never used multiple strategies and never did think about on how to configure it with the commit message checker.

**Comment by gilbertsoft** [comment]
But the rest of your configuration makes sense and looks good now!

**Comment by gilbertsoft** [comment]
One little thing: because the title you check should be on the first line you should also add `flags: ''` there like I did. With the default setting `gm` every line can contain the title and I hardly guess that's wrong.

**Comment by ernestkamara** [comment]
Thanks, @gilbertsoft.
My team and I have agreed on not enforcing specific merge strategies. So this will be hard to fix, but I will try with two different checks as started.

**Comment by gilbertsoft** [comment]
As far as I know @ItaloYeltsin also uses multiple strategies and perhaps is willing to give you some insights...

**Comment by ItaloYeltsin** [comment]
Hello @gilbertsoft and @ernestkamara, 

Sorry for the late response guys. I never use squash and merge, once I always try hard to keep changes logical, atomic and working per commit. It is like telling all the history behind the change that can come from a pull request. That's why a contributed with #17.  However, depending on the size of the project, it is kinda hard to control this, also, it take a little while to get used to it.

@ernestkamara, so your problem now is that when you receive news commits to your PR, the checker keep checking only the old ones, right?

**Comment by ernestkamara** [comment]
Hi @ItaloYeltsin, Thanks for your feedback. We have a big project and a big team. So I have now simplified the workflow below based on your pr https://github.com/TotalCross/totalcross/pull/117/files. 

Works fine:

Final Workflow
```
name: 'Check Commit Message'
on: [push, pull_request]
jobs:
  check-commit-message:
    name: Check Commit Message
    runs-on: ubuntu-latest
    steps:
      - name: Check Type
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: '^(add|remove|fix|chore)\([^\{\}\[\]\(\)]+?\) : '
          flags: ''
          error: 'Your first line has to contain a commit type like "add|remove|fix|chore(...) : ".'

      - name: Check Title Length
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: '^[^\s]+([ \t]+[^\s]+){2,}[ \t]*(\n.*)?$'
          flags: 's'
          error: 'A meaningful title should contain at least 3 words.'

      - name: Check Title Line Separator
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: '^[^\n]+(\n\n.+)?$'
          flags: 's'
          error: 'Should leave an empty line after title.'

      - name: Check Line Length
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: '^([^\n]{1,80}|Merge pull request.*)(\n.*)?$'
          flags: 's'
          error: 'The maximum title line length of 80 characters is exceeded.'

      - name: Check Footer
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: '^(Closes|Fixes) : \#((?!([A-Z0-9a-z]{1,10})-?$)[A-Z]{1}[A-Z0-9]+-[1-9][0-9]*).+$'
          error: 'You need at least one "Closes|Fixes : #<Jira issue key>" line.'
```

**Comment by ernestkamara** [comment]
@gilbertsoft, closing this question now! Thanks

**Comment by gilbertsoft** [comment]
Nice you got it working!
