### ISSUE TITLE
Ignore Github UI commits

### ISSUE THREAD

**Issue by SimonHarmonicMinor** [GsActions/commit-message-checker#42]
Is it possible to ignore Github UI commits? For example, something like `Merge branch 'master' into codestyle/#113-check-commits`

**Comment by gilbertsoft** [comment]
Yes should be possible with something like this:
`(Merge branch .*|PUT YOUR DEFAULT RULE HERE)`

Just replace `PUT YOUR DEFAULT RULE HERE` with your existing rule.

**Comment by gilbertsoft** [comment]
@SimonHarmonicMinor does this help you and can we close the issue?

**Comment by SimonHarmonicMinor** [comment]
@gilbertsoft, it helps, thanks. You can close it
