### ISSUE TITLE
please create full version release(s)

### ISSUE THREAD

**Issue by chrisjohnson00** [GsActions/commit-message-checker#47]
I have a disdain for the "floating" versions that are supported by actions.  Could you create a full release version for this as well?  

I've been burnt by using `v1` style versions with other 3rd party actions.  

Just to be clear, in case you aren't sure what I mean:

`v1` is both a version and an alias.  It can be aliased to `v1.0.0` and when `v1.0.1` comes out it aliases to `v1.0.1`.  When `v1.1.0` comes out `v1` is now an alias to `v1.1.0`.

I've had issues where an action was promoted from `v5.4` to `v5.5` and it stops working due to a bug.  In this case I was using `v5` and suddenly my workflows were failing without any change to them.

While I'm a huge supporter of semver, I also need to have the confidence that things are not changing without my knowledge.  I've since required (in my work environment) that we use full versions of actions when possible, and do a round of testing when upgrading actions.

Thank you for your contribution to actions, this one will be helpful to us :D

**Comment by gilbertsoft** [comment]
Please check the tags, there is one for each release and v1 points to the latest https://github.com/GsActions/commit-message-checker/tags

**Comment by gilbertsoft** [comment]
@chrisjohnson00 does this help?

**Comment by chrisjohnson00** [comment]
> Please check the tags, there is one for each release and v1 points to the latest https://github.com/GsActions/commit-message-checker/tags

V1 points to 0.5? Is that correct?

**Comment by gilbertsoft** [comment]
> 
> 
> > Please check the tags, there is one for each release and v1 points to the latest https://github.com/GsActions/commit-message-checker/tags
> 
> V1 points to 0.5? Is that correct?

Yes exactly. As you can see both tags are pointing to the same commit:

![grafik](https://user-images.githubusercontent.com/25326036/129698602-80d0f32f-a890-4860-b233-fdf8a110972f.png)


Maybe it's time for the 1.0.0 release. For the time being this action was still experimental.

**Comment by chrisjohnson00** [comment]
> Yes exactly. As you can see both tags are pointing to the same commit:

I'm curious what dependabot would do when `v1` is `v0.5.0`
The team implemented the action with it pulling `v0.5.0`, and it went into our workflow today, so I guess I'll keep an eye on what dependabot does with this once it runs later today.

**Comment by chrisjohnson00** [comment]
> I'm curious what dependabot would do when `v1` is `v0.5.0`
> The team implemented the action with it pulling `v0.5.0`, and it went into our workflow today, so I guess I'll keep an eye on what dependabot does with this once it runs later today.

Yes, Dependabot thinks that `v1` is newer than `v0.5.0` and created a PR to make that update.  I have instructed Dependabot to ignore this update, but if you are able to create a `v1.0.0` tag that would be great too.

**Comment by gilbertsoft** [comment]
Okay, will take care the next days to create a 1.0.0 tag...

**Comment by gilbertsoft** [comment]
Fyi https://github.com/GsActions/commit-message-checker/releases/tag/v1.0.0
