### ISSUE TITLE
Error: No commits found in the payload

### ISSUE THREAD

**Issue by gomex** [GsActions/commit-message-checker#6]
I am using this action in my workflow:

```
name: 'Commit Message Check'
on: [push]

jobs:
  check-commit-message:
    name: Check Commit Message
    runs-on: ubuntu-latest
    steps:

      - name: Check Commit Type
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: '^[\(\)\-a-z0-9,\s]+: .+(?:\n(?:\n.+)+)?(?:\n\n.+)?$'
          error: 'Your message must have the correct format "<scope>: <subject>" with an optional body and footer separated by blank lines.'
```

And it is falling with this msg:

```
##[error]Error: No commits found in the payload.
##[error]No commits found in the payload.
```

Here is the commit: https://github.com/shellhub-io/shellhub/commit/2a40e9682d9857df02e16debaf4fc9904e9c20df

My guess is something related to this msg: "This commit does not belong to any branch on this repository", but based on error msg it is something else.

**Comment by gilbertsoft** [comment]
Hey @gomex , I hardly guess there was a force push involved and this also could be the reason for the message _This commit does not belong to any branch on this repository_. But I currently have no idea why the payload does not get any commits assigned.
My best solution I currently have in mind is to just ignore such cases, means simply write a warning to the log and continue. I have to check if I can somehow mark the checks of this type of pushes as skiped.

**Comment by gilbertsoft** [comment]
Just found the real "error", a tag was involved. So a new tag was pushed to the branch which imho can be ignored by the commit message checker at all.
![grafik](https://user-images.githubusercontent.com/25326036/90498424-96ac7180-e148-11ea-8b0b-c6582023db02.png)

**Comment by gilbertsoft** [comment]
This issue should be solved with the current release.
