### ISSUE TITLE
Commit ammedment is not working

### ISSUE THREAD

**Issue by manavtidhan** [GsActions/commit-message-checker#76]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### GitHub-hosted runner

ubuntu-latest

### Current Behavior

After github action failed as it didnot find the regex in the commit message . but it still failed when commit message are rewrited and pushed.

### Expected Behavior

It should pass if the commit message is updated as per the regex

### Steps To Reproduce

I have put regex like below 

```
      - name: Check Jira ID or Skip tag
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: '(ED-[\d]+|TECH)'
          checkAllCommitMessages: 'true'
          accessToken: ${{ secrets.GITHUB_TOKEN }}
          error: 'You need at least Jira ID or Skip tag i.e [ED-123] | [skip|no issue].'
```

so to reproduce the problem , you can commit a message without the Jira ID i,e ED-123 , this one will fail which is expected but when you ammend your pushed commit then it should passed.

**Comment by gilbertsoft** [comment]
Hi @manavtidhan , thanks for your report. Please head to the debugging section at https://github.com/GsActions/commit-message-checker#troubleshooting-and-debugging and check why the action is failing. I currently guess it fails at the PR title and not the commit message.

**Comment by gilbertsoft** [comment]
Closing because of no feedback.
