### ISSUE TITLE
Use Node16 instead of Node12

### ISSUE THREAD

**Issue by jasonk619** [GsActions/commit-message-checker#81]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you willing to sponsor your idea?

- [ ] Yes, I like to sponsor this request

### Is your feature request related to a problem? Please describe

See https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

### Describe the solution you'd like

Update action to use Node 16 instead of Node 12

**Comment by gilbertsoft** [comment]
Available with https://github.com/GsActions/commit-message-checker/releases/tag/v2.0.0
