### ISSUE TITLE
Upgrade to node 16

### ISSUE THREAD

**Issue by CfirTsabari** [GsActions/commit-message-checker#99]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you willing to sponsor your idea?

- [ ] Yes, I like to sponsor this request

### Is your feature request related to a problem? Please describe

GitHub actions will deprecate the use of node 12 starting on September 27th,
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

### Describe the solution you'd like

Upgrade to node 16

**Comment by gilbertsoft** [comment]
Hi @CfirTsabari , please use v2.
